import { gsap } from "gsap";
import { DrawSVGPlugin } from "gsap/DrawSVGPlugin";

gsap.registerPlugin(DrawSVGPlugin);

export let screenAppearsTL = gsap.timeline();

screenAppearsTL.from("#main-circle",{duration:2, drawSVG: 0},"panel appears")
                .from("#a-button",{duration:2, drawSVG: 0},"panel appears")
                .from("#b-button",{duration:2, drawSVG: 0},"panel appears")
                .from("#c-button",{duration:2, drawSVG: 0},"panel appears")
                .from("#d-button",{duration:2, drawSVG: 0},"panel appears")
                .from("#e-button",{duration:2, drawSVG: 0},"panel appears")
                .from("#f-button",{duration:2, drawSVG: 0},"panel appears")
                .from("#g-button",{duration:2, drawSVG: 0},"panel appears")
                .from("#a-button-label",{duration:1, alpha:0},"panel numbers appear")
                .from("#b-button-label",{duration:1, alpha:0},"panel numbers appear")
                .from("#c-button-label",{duration:1, alpha:0},"panel numbers appear")
                .from("#d-button-label",{duration:1, alpha:0},"panel numbers appear")
                .from("#e-button-label",{duration:1, alpha:0},"panel numbers appear")
                .from("#f-button-label",{duration:1, alpha:0},"panel numbers appear")
                .from("#g-button-label",{duration:1, alpha:0},"panel numbers appear")
                .from("#control-panel-box",{duration:1, alpha:0},"panel numbers appear")
                .from("#control-panel-label",{duration:1, alpha:0},"panel numbers appear")
                .from("#a-indicator",{duration:.25, alpha:0})
                .from("#b-indicator",{duration:.25, alpha:0},"speed appears")
                .from("#c-indicator",{duration:.25, alpha:0})
                .from("#d-indicator",{duration:.25, alpha:0})
                .from("#e-indicator",{duration:.25, alpha:0})
                .from("#f-indicator",{duration:.25, alpha:0})
                .from("#g-indicator",{duration:.25, alpha:0})
                .from("#speed-dial",{duration:2, drawSVG: 0},"panel numbers appear")
                .from("#speed-label",{duration:1, alpha: 0},"speed appears")
                .from("#speed-ticks",{duration:2, alpha: 0},"speed appears")
                .from("#mph",{duration:2, alpha: 0},"speed appears")
                .from("#speed-numbers-1",{duration:2, alpha: 0},"speed appears")
                .from("#fuel-label",{duration:2, alpha: 0},"speed appears")
                .from("#e-empty",{duration:.25, alpha: 0},"speed appears")
                .from("#gas-symbol",{duration:.25, alpha: 0},"speed appears")
                .from("#f-full",{duration:.25, alpha: 0},"speed appears")
                .from("#fuel-1",{duration:.25, alpha: 0})
                .from("#fuel-2",{duration:.22, alpha: 0})
                .from("#fuel-3",{duration:.2, alpha: 0})
                .from("#fuel-4",{duration:.17, alpha: 0})
                .from("#fuel-5",{duration:.15, alpha: 0})
                .from("#fuel-6",{duration:.12, alpha: 0})
                .from("#fuel-7",{duration:.12, alpha: 0})
                .from("#fuel-8",{duration:.1, alpha: 0})
                .from("#fuel-9",{duration:.1, alpha: 0})
                .from("#fuel-10",{duration:.1, alpha: 0})
                .from("#fuel-11",{duration:.08, alpha: 0})
                .from("#fuel-12",{duration:.08, alpha: 0})
                .from("#fuel-13",{duration:.05, alpha: 0})
                .from("#fuel-14",{duration:.05, alpha: 0})
                .from("#fuel-15",{duration:.05, alpha: 0})
                .from("#music-box",{duration:1, alpha: 0},"music stuff")
                .from("#album-cover",{duration:2, alpha: 0},"music stuff")
                .from("#song-name",{duration:1, alpha: 0},"music stuff")
                .from("#artist-name",{duration:1.5, alpha: 0},"music stuff")
                .from("#song-bar",{duration:.5, alpha: 0},"music stuff")
                .from("#song-start-time",{duration:.5, alpha: 0},"music stuff")
                .from("#song-end-time",{duration:.5, alpha: 0},"music stuff")
                .from("#time-circle",{duration:.5, alpha: 0},"music stuff")
                .to("#time-circle",{duration:.5, x:"+=15"},"music stuff")
                .from("#pause-button",{duration:.5, alpha: 0},"music stuff")
                .from("#skip-button",{duration:.5, alpha: 0},"music stuff")
                .from("#go-back-button",{duration:.5, alpha: 0},"music stuff");